<?php

namespace App\Services;

class HaberesImponiblesService
{
    public function getHaberesImpobibles()
    {
        return [
            ['descripcion' => "Sueldo Base"],
            ['descripcion' => "Bonif.Personal"],
            ['descripcion' => "Asig.D.L. 25671"],
            ['descripcion' => "Asig. D.S.081"],
            ['descripcion' => "Asg.Edc.Sup.no."],
            ['descripcion' => "DS154-91-PCM"],
            ['descripcion' => "Bon.Dif. x Zona"],
            ['descripcion' => "Bonif. Familiar"],
            ['descripcion' => "D.U. 080-94"],
            ['descripcion' => "Refrig. y Mov."],
            ['descripcion' => "Movilidad"],
            ['descripcion' => "Bon. D.U. 90-96"],
            ['descripcion' => "DS. 019-94-PCM"],
            ['descripcion' => "Ensenanza"],
            ['descripcion' => "Contrato"],
            ['descripcion' => "CVid.DS154-91EF"],
            ['descripcion' => "Bon.Esp.Dir."],
            ['descripcion' => "Grat.Aguinaldo"],
            ['descripcion' => "Bonif.Escolar"],
            ['descripcion' => "Bon. Especial"],
            ['descripcion' => "Reunificada"],
            ['descripcion' => "Bonif.Direcc."],
            ['descripcion' => "Bon.T.Serv."],
            ['descripcion' => "Sepelio y luto"],
            ['descripcion' => "Bonif x propin."],
            ['descripcion' => "AFP - DL 26504"],
            ['descripcion' => "Grat.T.Serv."],
            ['descripcion' => "Cred.Deveng."],
            ['descripcion' => "Pen.Rem.Bas."],
            ['descripcion' => "GP-CTO"],
            ['descripcion' => "Cargo adicional"],
            ['descripcion' => "Rein Basica"],
            ['descripcion' => "Rein.Bon.Pers."],
            ['descripcion' => "Rein DL 25671"],
            ['descripcion' => "Rein.DS081-93EF"],
            ['descripcion' => "Rein.Asg.Esp."],
            ['descripcion' => "Reint. TPH"],
            ['descripcion' => "Rein.Frontera"],
            ['descripcion' => "Reint.Bon.Fam."],
            ['descripcion' => "Rein.Urg.080-94"],
            ['descripcion' => "Rein.Refrig.Mov"],
            ['descripcion' => "Reint.Movil."],
            ['descripcion' => "Rein.D.U. 90-96"],
            ['descripcion' => "Rein.DS019-94"],
            ['descripcion' => "Rein.Ensenanza"],
            ['descripcion' => "Reint. Contrato"],
            ['descripcion' => "Reint.Cost Vida"],
            ['descripcion' => "Rein.Vacaciones"],
            ['descripcion' => "Rein.Bon.Direct"],
            ['descripcion' => "Reint.GratAguin"],
            ['descripcion' => "Rein.Bon.Escola"],
            ['descripcion' => "Rein.prep.clase"],
            ['descripcion' => "Reunificada"],
            ['descripcion' => "Rein.bon adic"],
            ['descripcion' => "Reint. CTS"],
            ['descripcion' => "Reint.Sepelio"],
            ['descripcion' => "Reint.DL25897"],
            ['descripcion' => "Reint. DL26504"],
            ['descripcion' => "Reint.Grat Serv"],
            ['descripcion' => "Reint.Devengado"],
            ['descripcion' => "Reint.pension"],
            ['descripcion' => "Reint.DL25030"],
            ['descripcion' => "Rein. Cargo Sim"],
            ['descripcion' => "Reint.gpcto"],
            ['descripcion' => "Reint.cargadic"],
            ['descripcion' => "Dif Pensionable"],
            ['descripcion' => "D.L.25897"],
            ['descripcion' => "D.L. 26504"],
            ['descripcion' => "Reint.Dif.Pens."],
            ['descripcion' => "D.U.073-97"],
            ['descripcion' => "DL817-ONP"],
            ['descripcion' => "Reint.DL817-ONP"],
            ['descripcion' => "Reint.DU-073-97"],
            ['descripcion' => "Diferencial"],
            ['descripcion' => "CredDevNaf"],
            ['descripcion' => "Reintegro Aut."],
            ['descripcion' => "Reintg. Manual"],
            ['descripcion' => "Asig. Jud. I"],
            ['descripcion' => "Asig. Jud. II"],
            ['descripcion' => "Bon. Esp. DS059"],
            ['descripcion' => "Decimas Vac."],
            ['descripcion' => "djudicia"],
            ['descripcion' => "ojudicia"],
            ['descripcion' => "D.U.011-99"],
            ['descripcion' => "Horas adic."],
            ['descripcion' => "ENCARGATURA"],
            ['descripcion' => "ds135"],
            ['descripcion' => "DU105-2001"],
            ['descripcion' => "Ley 27617"],
            ['descripcion' => "Bonif. 27617"],
            ['descripcion' => "restribconst"],
            ['descripcion' => "difjud"],
            ['descripcion' => "LEY29035"],
            ['descripcion' => "Rein.MAf 28979"],
            ['descripcion' => "Rein.MAf 29035"],
            ['descripcion' => "Decima AfectDct"],
            ['descripcion' => "Rem.Int.Mensua"],
            ['descripcion' => "DS Nº 005-90"],
            ['descripcion' => "Rem.Mensual"],
            ['descripcion' => "Horas.Adic"],
            ['descripcion' => "Nivelacion IPSS"],
            ['descripcion' => "DS 153-91-EF"],
            ['descripcion' => "ds031-2011-EF"],
            ['descripcion' => "Ley29702"],
            ['descripcion' => "asig.direc.cont"],
            ['descripcion' => "RIM_Ley 29944"],
            ['descripcion' => "Pension_DL20530"],
            ['descripcion' => "Agui_Extraord"],
            ['descripcion' => "Vac_T_Afect"],
            ['descripcion' => "BONO1_RM548-15"],
            ['descripcion' => "RMS_30372"],
            ['descripcion' => "Ley 30372-89"],
            ['descripcion' => "RM_Aux"],
            ['descripcion' => "RM_Aux_Cont"],
            ['descripcion' => "Reint. Ley30512"],
            ['descripcion' => "RIMS"],
            ['descripcion' => "Rem.Transi.ESFA"],
            ['descripcion' => "RIMS_Transit"],
            ['descripcion' => "RMS_30512"],
            ['descripcion' => "Reint_RIM"],
            ['descripcion' => "H_CAS"],
            ['descripcion' => "CTS_Cont"],
            ['descripcion' => "Luto_Cont"],
            ['descripcion' => "Plan_recup_afec"],
            ['descripcion' => "Ley30693_RMV"],
            ['descripcion' => "10 RMV"],

            ['descripcion' => "ds009-2019-EF"],
            ['descripcion' => "ds006-2020-EF"],
            ['descripcion' => "ds006-2021-EF"],
            ['descripcion' => "ds014-2022-EF"],
            ['descripcion' => "ds007-2023-EF"],

        ];
    }
}
